using ACCODocs.Logic.LinkLibrary;

namespace ACCODocs
{
    /// <summary>
    /// The ONE ribbon button for this add-in: toggles the Link Library dockable pane
    /// (DockablePane.Show()/Hide(), spec section 3). All other UI lives inside the pane.
    /// The pane itself is registered at startup by LinkLibraryPaneRegistrar — this
    /// command only resolves and toggles it.
    /// </summary>
    [Transaction(TransactionMode.Manual)]
    public class Cmd_ACCODocs : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            UIApplication uiapp = commandData.Application;

            DockablePane pane = LinkLibraryPaneRegistrar.TryGetPane(uiapp);
            if (pane == null)
            {
                message = "The Link Library pane is not registered in this Revit session.";
                TaskDialog.Show(LinkLibraryPaneRegistrar.PaneTitle,
                    "The Link Library pane could not be found. It registers when Revit starts — " +
                    "if the add-in was just installed, restart Revit.");
                return Result.Failed;
            }

            if (pane.IsShown())
                pane.Hide();
            else
                pane.Show();

            return Result.Succeeded;
        }

        internal static PushButtonData GetButtonData()
        {
            // use this method to define the properties for this command in the Revit ribbon
            string buttonInternalName = "btnACCODocs";
            string buttonTitle = "ACCO Docs";

            // Icon: stacked sheets + ACCO-blue bookmark, generated by the prompticon skill from
            // Resources\svg\ACCODocs.svg (light + dark theme variants rendered from the same SVG).
            Common.ButtonDataClass myButtonData = new Common.ButtonDataClass(
                buttonInternalName,
                buttonTitle,
                MethodBase.GetCurrentMethod().DeclaringType?.FullName,
                Properties.Resources.ACCODocs_32x32,
                Properties.Resources.ACCODocs_16x16,
                Properties.Resources.ACCODocs_Dark_32x32,
                Properties.Resources.ACCODocs_Dark_16x16,
                "Show or hide the ACCO Link Library — searchable documentation, reference links, and quick Revit commands.");

            // Extended tooltip (shows after hovering a moment longer).
            myButtonData.Data.LongDescription =
                "Library tab: browse the shared ACCO library, or search by title, description, tags, " +
                "and web address. Double-click a link to open it; right-click to copy it or add it to your favorites.\n\n" +
                "Pick Element: select an element (or pick one) to see links related to its category, family, and system.\n\n" +
                "My Links tab: your favorites, recent links, and personal links organized into your own categories — " +
                "with export/import for backup and sharing.\n\n" +
                "Links can open web pages, files, folders, Box content, and even run Revit commands. " +
                "Library content updates automatically from the shared ACCO master — no reinstall needed.";

            return myButtonData.Data;
        }
    }

}
